"""added ai_intent in project table

Revision ID: 9d8198b896f6
Revises: d9daf9c57cf3
Create Date: 2026-01-05 13:31:05.201517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8198b896f6'
down_revision = 'd9daf9c57cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_intent', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('ai_intent')

    # ### end Alembic commands ###
