"""Add AI fields to Projects model

Revision ID: d9daf9c57cf3
Revises: b3546fe02940
Create Date: 2026-01-05 13:10:27.262690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9daf9c57cf3'
down_revision = 'b3546fe02940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_output', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_output_version', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ai_generated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('ai_generated_at')
        batch_op.drop_column('ai_output_version')
        batch_op.drop_column('ai_output')

    # ### end Alembic commands ###
