"""made update in summary fields

Revision ID: ea8a3d33a218
Revises: 9d8198b896f6
Create Date: 2026-01-05 14:06:55.122587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8a3d33a218'
down_revision = '9d8198b896f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_summary_version', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ai_summary_generated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('ai_output_version')
        batch_op.drop_column('ai_generated_at')
        batch_op.drop_column('ai_output')
        batch_op.drop_column('ai_intent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_intent', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('ai_output', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ai_generated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('ai_output_version', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('ai_summary_generated_at')
        batch_op.drop_column('ai_summary_version')
        batch_op.drop_column('ai_summary')

    # ### end Alembic commands ###
