"""Added tech stack and repo url to projects

Revision ID: f9d8c8c631fb
Revises: b112f4199d75
Create Date: 2026-01-01 15:23:27.128291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d8c8c631fb'
down_revision = 'b112f4199d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tech_stack', sa.String(length=225), nullable=True))
        batch_op.add_column(sa.Column('repo_url', sa.String(length=225), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('repo_url')
        batch_op.drop_column('tech_stack')

    # ### end Alembic commands ###
